INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("John", "Smith", "83012217938");

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("Curtis", "Wilson", "75121002790");

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("Cathy", "Booker", "90112801727");

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("Marissa", "Cain", "84061908044");

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID)
     VALUES ("Muriel", "Fulton", "76081409269");

COMMIT;

INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("The Stranger", 1942);

INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("in Search of Lost Time", 1927);

INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("The Trial", 1925);

INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("The Little Prince", 1943);

INSERT INTO BOOKS(TITLE, PUBYEAR)
     VALUES ("Man's Fate", 1933);

COMMIT;

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (1, 1, CURDATE() - 10, null);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (2, 1, CURDATE() - 10, null);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (4, 1, CURDATE() - 10, CURDATE() - 5);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (1, 3, CURDATE() - 8, null);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (5, 3, CURDATE() - 4, CURDATE() - 2);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (5, 4, CURDATE() - 10, CURDATE() - 8);

INSERT INTO RENTS(BOOK_ID, READER_ID, RENT_DATE, RETURN_DATE)
     VALUES (5, 5, CURDATE() - 8, null);

COMMIT;